[phases.setup]
nixPkgs = [
  "zlib.dev",
  "libjpeg.dev",
  "libpng.dev",
  "freetype.dev",
  "pkg-config",
  "mesa",          # <-- ini penting: untuk libGL.so.1
  "gcc",
  "gnumake",
  "python312",
  "python312Packages.setuptools",
  "python312Packages.wheel",
  "python312Packages.pip"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]
